### PR TITLE
Tweak M74 rocket stacklimit and stacked graphic display

### PR DESCRIPTION
**Pull request by sumghai**
For #1037 

Changes the display of stacked M74 rockets to better emulate the real-life appearance of 4 rockets in an complete en bloc clip:
* Reduce stackLimit to 24 (a multiple of 4)
* Change the graphicClass to the new `CombatExtended.Graphic_StackCountRanged` (introduced from the FastTrack merger)
* Rename the M74 ammo textures so that their filenames can be parsed by `Graphic_StackCountRanged` to display the appropriate texture at intermediate stack counts

### CODE REVIEW

**Comment by zozilin** [comment]
I am okay with the graphic change. Stack limit change to 24 is very minor but it disrupts spreadsheet uniformity. 
What about a compromise - implement graphics, but keep stack limit as is?

**Comment by sumghai** [comment]
Since the crafting recipe is currently set to 4 rockets per bill, if we keep the `stackLimit` to 25, we may have an odd situation where upon crafting the seventh iteration of the bill, one would end up with one full stack of 25 M74s, with 3 M74s left over.

**Comment by Alicecomma** [comment]
That is a problem with the recipe system, and having a few rockets left-over is never really a problem

**Comment by sumghai** [comment]
I have just reverted the `stackLimit` to 25, while keeping the graphics class changes.

**Pull request merged**
